#!/usr/bin/env python3
import sys
import os
import subprocess

# KDE Connect handler compatibility shim for PC Connect
args = sys.argv[1:]
send_bin = os.path.expanduser("~/.local/bin/pc-connect-send")

files = []
skip_next = False
for a in args:
    if skip_next:
        skip_next = False
        continue
    if a in ('--device', '-d'):
        skip_next = True
        continue
    if a.startswith('--'):
        continue
    files.append(a)

if files and os.path.exists(send_bin):
    res = subprocess.run([send_bin] + files)
    sys.exit(res.returncode)
else:
    sys_handler = "/usr/bin/kdeconnect-handler"
    if os.path.exists(sys_handler) and os.path.realpath(sys_handler) != os.path.realpath(__file__):
        res = subprocess.run([sys_handler] + args)
        sys.exit(res.returncode)
